### ISSUE TITLE
Crash app when run app.

### ISSUE THREAD

**Issue by ltvu93** [NYTimes/Register#58]
App crash when i try to run. This is log file. And I can't install RegisterCompanion apk.

2018-11-02 18:00:31.550 20130-20130/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nytimes.android.external.register.sample, PID: 20130
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nytimes.android.external.register.sample/com.nytimes.android.external.register.sample.SampleActivity}: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3061)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
        at android.os.Handler.dispatchMessage(Handler.java:114)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6716)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.android.billingclient.api.BillingClientTesting$BillingContextWrapper.bindService(BillingClientTesting.java:120)
        at com.android.billingclient.api.BillingClientImpl.startConnection(BillingClientImpl.java:237)
        at com.android.billingclient.api.BillingClientTesting.startConnection(BillingClientTesting.java:53)
        at com.nytimes.android.external.registerlib.GoogleServiceProviderTesting.startConnection(GoogleServiceProviderTesting.java:37)
        at com.nytimes.android.external.register.sample.SampleActivity.initGoogleServiceProvider(SampleActivity.java:189)
        at com.nytimes.android.external.register.sample.SampleActivity.onCreate(SampleActivity.java:80)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2906)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3061) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
        at android.os.Handler.dispatchMessage(Handler.java:114) 
        at android.os.Looper.loop(Looper.java:198) 
        at android.app.ActivityThread.main(ActivityThread.java:6716) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by goldstei** [comment]
Thanks for this report.  Are you testing on an emulator? This exception (which Register should handle better) occurs if billing services are not available. A common case of this is an emulator instance that does not include play services. If this is not your situation, please provide more detail.

**Comment by ltvu93** [comment]
Finally, I can run app success. Above error happen when I try to enable register backend before install companion app. But You need update companion apk link, It still in version 0.0.1. I must build directly from project to make it work properly.

**Comment by wdziemia** [comment]
Updated the companion app to the latest master. Sorry about that! 

https://github.com/NYTimes/Register/releases/tag/0.0.1
