### ISSUE TITLE
Companion app keeps crashing

### ISSUE THREAD

**Issue by TheRealAgentK** [NYTimes/Register#60]
After solving #59 with a new .apk file, the Compaion app keeps crashing on launch.

Behaviour:

Without register.json, app comes up fine and shows a text field prompting the user to put a register.json to sdcard/ .

Even with the provided json sample from the README page, the app crashes, doesn't even come up with any UI. 

File content:

```
{
  "skus": {
    "register.sample.iap": {
      "type": "inapp",
      "price" : "1.00",
      "title" : "Sample In App Purchase Item",
      "description" : "This is an in app purchase item for use with Register sample app",
      "package" : "com.nytimes.android.external.register"
    },
    "register.sample.sub": {
      "type": "subs",
      "price" : "10.00",
      "title" : "Sample Subscription Item1",
      "description" : "This is a subscription item for use with Register sample app",
      "package" : "com.nytimes.android.external.register"
    }
  },
  "users": [
    "user1@register.nytimes.com",
    "user2@register.nytimes.com"
  ]
}
```

File name:

register.json

Location:

/sdcard

**Comment by TheRealAgentK** [comment]
Ah, turns out this comes from a GSON parsing issue:

    Process: com.nytimes.android.external.register, PID: 5854
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nytimes.android.external.register/com.nytimes.android.external.register.MainActivity}: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Cannot build ConfigSku, some of required attributes are not set [itemType]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Cannot build ConfigSku, some of required attributes are not set [itemType]
        at com.google.gson.Gson.fromJson(Gson.java:899)
        at com.google.gson.Gson.fromJson(Gson.java:825)
        at com.nytimes.android.external.register.di.ActivityModule.provideConfig(ActivityModule.java:55)
        at com.nytimes.android.external.register.di.ActivityModule_ProvideConfigFactory.get(ActivityModule_ProvideConfigFactory.java:30)
        at com.nytimes.android.external.register.di.ActivityModule_ProvideConfigFactory.get(ActivityModule_ProvideConfigFactory.java:11)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.nytimes.android.external.register.MainActivity_MembersInjector.injectMembers(MainActivity_MembersInjector.java:46)
        at com.nytimes.android.external.register.MainActivity_MembersInjector.injectMembers(MainActivity_MembersInjector.java:9)
        at com.nytimes.android.external.register.di.DaggerApplicationComponent$ActivityComponentImpl.inject(DaggerApplicationComponent.java:215)
        at com.nytimes.android.external.register.MainActivity.inject(MainActivity.java:79)
        at com.nytimes.android.external.register.MainActivity.onCreate(MainActivity.java:65)
        at android.app.Activity.performCreate(Activity.java:6999)
        at android.app.Activity.performCreate(Activity.java:6990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     Caused by: java.lang.IllegalStateException: Cannot build ConfigSku, some of required attributes are not set [itemType]
        at com.nytimes.android.external.register.model.ImmutableConfigSku$Builder.build(ImmutableConfigSku.java:314)
        at com.nytimes.android.external.register.model.GsonAdaptersConfigSku$ConfigSkuTypeAdapter.readConfigSku(GsonAdaptersConfigSku.java:83)
        at com.nytimes.android.external.register.model.GsonAdaptersConfigSku$ConfigSkuTypeAdapter.read(GsonAdaptersConfigSku.java:56)
        at com.nytimes.android.external.register.model.GsonAdaptersConfigSku$ConfigSkuTypeAdapter.read(GsonAdaptersConfigSku.java:30)
        at com.nytimes.android.external.register.model.GsonAdaptersConfig$ConfigTypeAdapter.readInSkus(GsonAdaptersConfig.java:128)
        at com.nytimes.android.external.register.model.GsonAdaptersConfig$ConfigTypeAdapter.eachAttribute(GsonAdaptersConfig.java:104)
        at com.nytimes.android.external.register.model.GsonAdaptersConfig$ConfigTypeAdapter.readConfig(GsonAdaptersConfig.java:92)
        at com.nytimes.android.external.register.model.GsonAdaptersConfig$ConfigTypeAdapter.read(GsonAdaptersConfig.java:61)
        at com.nytimes.android.external.register.model.GsonAdaptersConfig$ConfigTypeAdapter.read(GsonAdaptersConfig.java:32)

The sample JSON from README uses the property `type` for subscription or purchase and it seems `itemType` is required. I can see there was a change in May 2018 for the 0.0.3 release, but I'm at this stage not 100% sure yet if the documentation is just wrong and it should be `itemType`.

Changing my register.json to using `itemType` at least stops the companion app from crashing for now. But depending on what the actual root of the problem is, I might now see other issues when I want to integrate it all into my app :-)

**Comment by TheRealAgentK** [comment]
Ok... so - if I wanted to use it now then, would it be better if I build it from the repo based on master myself instead of using the 0.0.3 companion app?

**Comment by wdziemia** [comment]
Stick w/ 0.0.3 if you're not using the play billing library. If you are, then try out master. Just a note, it's a work in progress. If you run into an issue then feel free to open a PR. We've been busy on our side and had to hold off on the next release, but plan on getting to it as soon as we can!

If you want something more stable, I'd recommend checking out BillingX by Ryan Harter! https://github.com/pixiteapps/billingx. It's a similar lib but is simpler with it's approach (no companion app) and is for the play-billing-library!

**Comment by TheRealAgentK** [comment]
Cool, got it working with the sample as a fresh build from master for now. I'll let you know how I go with my actual project.

**Comment by wdziemia** [comment]
sounds good!

**Comment by TheRealAgentK** [comment]
So, it seems to work ok as long as I build the sample app with the companion app both from master. 

Things start to fall apart quite badly when I try to use 0.0.5 or 0.0.6 (or 0.0.3 even) in my own projects from jcenter. It seems that individuals have released .5 from a branch, .6 I couldn't even find where that's from, sadly.

In short - it's a struggle and I start to wonder if it's really worthwhile the time and effort trying to untangle all of it as an outsider of your team at this stage. Which is sad, because the idea and the project are great.

**Comment by wdziemia** [comment]
This project is not yet stable, which the current versioning resembles. `0.0.3` is the latest that I'd consider "stable", but we are not yet at a `1.0`. This means that there is a good chance of future breaking changes, like that of `item` renamed to `itemType`. 

`0.0.3` release does not support the play billing library, but `master` does.

We are working towards `1.0` however, once we get bandwidth internally.

0.0.5 was a "silent" release, needed internally for a feature that was shipped in the NYTimes app. There are conflicts w/ master which is why it is currently waiting to be merged into master.

If you're up for it, we'd love and appreciate any help we can get. We'd love a PR for merging the `0.0.5` back into master, or even help writing tests for the play-billing library that was merged. 

Like I mentioned, there is https://github.com/pixiteapps/billingx that you could use to help test your purchase flows!
